// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "ContactSplitForm" section.

import React from 'react';
import ContactSplitForm from "@/components/sections/contact/ContactSplitForm";

export default function ContactSplitFormSection(): React.JSX.Element {
  return (
    <div data-webild-section="ContactSplitForm"><ContactSplitForm
        tag="EASY CHECKOUT"
        title="Complete Your Pickup Order"
        description="Provide your pickup details below and we will have your fresh Southern comfort food hot and ready at Taste And See."
        inputs={[{"name":"fullName","type":"text","placeholder":"Full Name","required":true},{"name":"phone","type":"tel","placeholder":"Phone Number for SMS updates","required":true},{"name":"email","type":"email","placeholder":"Email Address for receipt","required":true},{"name":"pickupTime","type":"text","placeholder":"Requested Pickup Time (e.g., 5:30 PM)","required":true}]}
        textarea={{"name":"orderNotes","placeholder":"Special instructions or dietary requests...","rows":3,"required":false}}
        buttonText="Place Pickup Order"
        imageSrc=""
        textAnimation="slide-up"
      /></div>
  );
}
