// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "ProductQuantityCards" section.

import React from 'react';
import ProductQuantityCards from "@/components/sections/product/ProductQuantityCards";

export default function ProductQuantityCardsSection(): React.JSX.Element {
  return (
    <div data-webild-section="ProductQuantityCards"><ProductQuantityCards
        tag="Add Extra Goodness"
        title="Complete Your Southern Feast"
        description="Add extra sides, homemade sweet treats, or fresh sweet tea to your order before completing checkout."
        primaryButton={{"text":"Proceed to Checkout","href":"#checkout-form"}}
        secondaryButton={{"text":"Back to Menu","href":"/menu"}}
        products={[{"price":"$4.99","name":"Smoked Mac & Cheese Side"},{"price":"$5.99","name":"Homemade Peach Cobbler"},{"price":"$3.50","name":"Southern Sweet Tea"},{"name":"Honey Butter Cornbread","price":"$3.99"}]}
        textAnimation="slide-up"
      /></div>
  );
}
