// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from "@/components/sections/contact/ContactCta";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
      <ContactCta
              tag="Place Your Order"
              text="Visit us at 6820 N Main St Ste E, Columbia, SC or call ahead to order!"
              primaryButton={{ text: "Call 803-401-5671", href: "tel:8034015671" }}
              secondaryButton={{ text: "Get Directions", href: "https://maps.google.com/?q=6820+N+Main+St+Ste+E+Columbia+SC" }}
              textAnimation="slide-up"
            />
    </div>
  );
}
