// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "footer" section.

import React from 'react';
import FooterSimple from "@/components/sections/footer/FooterSimple";

export default function FooterSection(): React.JSX.Element {
  return (
    <div id="footer" data-section="footer">
      <FooterSimple
              brand="Taste and See Soul Food"
              columns={[{ title: "Menu", items: [{ label: "Chef Specials", href: "#" }, { label: "Entrees", href: "#" }, { label: "Desserts", href: "#" }] }]}
              copyright="© 2025 Taste and See Soul Food Kitchen. All rights reserved."
              links={[{ label: "Terms", href: "#" }, { label: "Privacy", href: "#" }]}
            />
    </div>
  );
}
