// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "HeroBillboard" section.

import React from 'react';
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import AvatarGroup from "@/components/ui/AvatarGroup";

export default function HeroBillboardSection(): React.JSX.Element {
  return (
    <div data-webild-section="hero-billboard">
  <section aria-label="Hero section" className="relative pt-25 pb-12 md:pt-30">
    <HeroBackgroundSlot />
    <div className="flex flex-col gap-8 w-content-width mx-auto">
      <div className="flex flex-col items-center gap-3 text-center">
        <TextAnimation text="Hearty Southern Favorites Made Fresh Daily" variant="slide-up" gradientText={true} tag="h1" className="md:max-w-8/10 text-6xl md:text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-center text-balance" />
        <TextAnimation text="Explore our full menu of crispy fried chicken, tender baskets, golden fried fish, homestyle sides, and sweet specialty drinks. Made fresh with love and authentic Southern flavor." variant="slide-up" gradientText={false} tag="p" className="md:max-w-7/10 text-lg md:text-xl leading-snug text-balance" />
        <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
          <Button text="View Menu" href="#menu" variant="primary" />
          <Button text="Order Pickup" href="#order" variant="secondary" animationDelay={0.1} />
        </div>
      </div>
    </div>
  </section>
</div>
  );
}
