// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboard from "@/components/sections/hero/HeroBillboard";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
      <HeroBillboard
              tag="6820 N Main St Ste E • Columbia, SC"
              title="Taste and See Soul Food Kitchen Menu"
              description="Serving mouthwatering traditional soul food, seafood combos, whole wing baskets, homemade sides, and desserts."
              primaryButton={{ text: "Call to Order: 803-401-5671", href: "tel:8034015671" }}
              secondaryButton={{ text: "Visit Location", href: "https://maps.google.com/?q=6820+N+Main+St+Ste+E+Columbia+SC" }}
              imageSrc="https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070662778-t3nkrha7.webp?_wi=2"
              textAnimation="slide-up"
            />
    </div>
  );
}
