// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "product" section.

import React from 'react';
import ProductVariantCards from "@/components/sections/product/ProductVariantCards";

export default function ProductSection(): React.JSX.Element {
  return (
    <div id="product" data-section="product">
      <ProductVariantCards
        tag="Chef Specials & Favorites"
        title="Signature Soul Food Dishes"
        description="Includes Rice & Gravy, choice of 2 sides, bread, and a drink. Prices subject to change."
        products={[{"imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070671583-biua6861.webp","variant":"Rice & Gravy + 2 Sides + Drink","name":"Oxtails (Sat/Sun)","price":"$26.99"},{"price":"$24.99","imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070776575-ct31mfjl.webp","variant":"Rice & Gravy + 2 Sides + Drink","name":"Lobster Lamb Chops"},{"variant":"Rice & Gravy + 2 Sides + Drink","name":"Blackened Salmon","imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070727441-qfbye5ui.webp","price":"$24.99"},{"variant":"2 pc Fish, 6 Shrimp, 2 Sides, Hushpuppies","imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070681462-5gce7p6k.webp","price":"$25.99","name":"Flounder Seafood Combo"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070696743-9h6avbwq.webp","price":"$17.99","name":"3 pc Fried or Baked Chicken","variant":"Includes Rice & Gravy + 2 Sides"},{"price":"$22.49","name":"Fried or Baked Turkey Wings","imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070716976-o5kdj5a9.webp","variant":"Includes Rice & Gravy + 2 Sides"},{"variant":"Includes Rice & Gravy + 2 Sides","imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070662778-t3nkrha7.webp","price":"$20.99","name":"Smothered Pork Chops"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070766688-s9gi7mxo.webp","name":"BBQ Ribs","price":"$18.99","variant":"Includes Rice & Gravy + 2 Sides"}]}
        textAnimation="slide-up"
      />
    </div>
  );
}
