// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "ProductQuantityCards" section.

import React from 'react';
import ProductQuantityCards from "@/components/sections/product/ProductQuantityCards";

export default function ProductQuantityCardsSection(): React.JSX.Element {
  return (
    <div data-webild-section="ProductQuantityCards"><ProductQuantityCards
        tag="Southern Kitchen Menu"
        title="Fresh Cooked Comfort Plates"
        description="Hearty fried entrees, golden basket combos, homestyle sides, and sweet specialty drinks made fresh with authentic flavor."
        textAnimation="slide-up"
        primaryButton={{"text":"Order Now & Get 15% Off Today","href":"/ordering"}}
        secondaryButton={{"text":"View All Sides","href":"#sides"}}
        products={[{"name":"3 Pc Chicken Entree","price":"$19.06","imageSrc":"https://img.freepik.com/free-photo/crispy-fried-chicken-plate_144627-24543.jpg"},{"name":"3 Tender Basket","price":"$15.88","imageSrc":"https://img.freepik.com/free-photo/crispy-chicken-fingers-french-fries_144627-24538.jpg"},{"name":"Fried Fish (2 Pieces)","price":"$19.06","imageSrc":"https://img.freepik.com/free-photo/crispy-fried-fish-fillet-french-fries_144627-24560.jpg"},{"name":"6 Pc Shrimp Meal","price":"$15.88","imageSrc":"https://img.freepik.com/free-photo/crispy-fried-shrimp-basket_144627-24580.jpg"},{"name":"8 Pc Cut Wing Meal","price":"$20.12","imageSrc":"https://img.freepik.com/free-photo/spicy-chicken-wings-sauce_144627-24550.jpg"},{"name":"Fried Pork Chops","price":"$19.06","imageSrc":"https://img.freepik.com/free-photo/grilled-pork-chops-plate_144627-24520.jpg"},{"name":"2 Tender Kids Meal","price":"$10.58","imageSrc":"https://img.freepik.com/free-photo/chicken-tenders-fries-basket_144627-24535.jpg"},{"name":"Candied Yams","price":"$4.54","imageSrc":"https://img.freepik.com/free-photo/sweet-roasted-yams-dish_144627-24515.jpg"},{"name":"Leo’s Lemonade","price":"$3.16","imageSrc":"https://img.freepik.com/free-photo/iced-lemonade-glass-citrus-slice_144627-24590.jpg"},{"name":"Banana Pudding","price":"$4.22","imageSrc":"https://img.freepik.com/free-photo/sweet-banana-pudding-dessert-glass_144627-24600.jpg"}]}
      /></div>
  );
}
