// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "come-hungry" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ComeHungrySection(): React.JSX.Element {
  return (
    <div id="come-hungry" data-section="come-hungry">
        <SectionErrorBoundary name="come-hungry">
              <AboutTextSplit
          title="COME HUNGRY. LEAVE HAPPY."
          descriptions={[
            "At Taste And See Soul Food Kitchen, we believe good food should feel like home. We specialize in authentic Southern hospitality and recipes passed down through generations.",
            "From hearty soul-food plates to Southern favorites and unforgettable sides, every meal is made from scratch with care to satisfy your deepest craving.",
          ]}
          primaryButton={{
            text: "See The Menu",
            href: "#menu",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
