/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useState } from "react";
import Button from "@/components/ui/Button";
import SelectorButton from "@/components/ui/SelectorButton";
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Transition from "@/components/ui/Transition";
import Accordion from "@/components/ui/Accordion";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

const categories = [
  {
    name: "Visiting",
    items: [
      {
        question: "Where are you located?",
        answer: "We are located right in the heart of Columbia, South Carolina."
      },
      {
        answer: "Sunday: 1–7 PM\nMonday: 2–8 PM\nTuesday: Closed\nWednesday: Closed\nThursday: 12–8 PM\nFriday: 12–8 PM\nSaturday: 12–8 PM",
        question: "What are your hours of operation?"
      }
    ]
  },
  {
    name: "Ordering",
    items: [
      {
        answer: "Absolutely, reach out to us for your next event.",
        question: "Do you offer catering?"
      },
      {
        answer: "Yes, use our website to place your order.",
        question: "Can I order online?"
      }
    ]
  }
];

type FaqItem = {
  question: string;
  answer: string;
};

type FaqCategory = {
  name: string;
  items: FaqItem[];
};

interface FaqTabbedAccordionProps {
  tag: string;
  title: string;
  description: string;
  categories: FaqCategory[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
  cta?: {
    name: string;
    role: string;
    buttonText: string;
    buttonHref: string;
  } & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });
}

const FaqInline = () => {
  const [activeCategory, setActiveCategory] = useState(categories[0]?.name || "");

  const currentItems = categories.find((c) => c.name === activeCategory)?.items || [];
  const accordionItems = currentItems.map((item) => ({ title: item.question, content: item.answer }));

  return (
    <section aria-label="FAQ section" className="py-20">
      <div className="w-content-width mx-auto">
        <div className="card rounded flex flex-col gap-6 md:gap-10 p-6 md:p-10">
          <div className="flex flex-col items-center gap-2">
            <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
              <p>{"Information"}</p>
            </div>

            <TextAnimation
              text={"NEED TO KNOW"}
              variant={"fade-blur"}
              gradientText={true}
              tag="h2"
              className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
            />

            <TextAnimation
              text={"Common questions about our kitchen and how to get your hands on our food."}
              variant={"fade-blur"}
              gradientText={false}
              tag="p"
              className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
            />

            <SelectorButton
              options={categories.map((c) => ({ value: c.name, label: c.name }))}
              activeValue={activeCategory}
              onValueChange={setActiveCategory}
              className="mt-2 md:mt-3"
            />
          </div>

          <ScrollReveal variant="fade">
            <Transition key={activeCategory} whileInView={false} className="">
              <Accordion items={accordionItems} />
            </Transition>
          </ScrollReveal>

          {undefined && (
            <>
              <div className="w-full h-px bg-foreground/5" />
              <div className="flex flex-col md:flex-row md:items-center gap-6 justify-between">
                <div className="flex items-center gap-3">
                  <ImageOrVideo
                    imageSrc={undefined.imageSrc}
                    videoSrc={undefined.videoSrc}
                    className="size-10 md:size-11 2xl:size-12 rounded-full object-cover"
                  />
                  <div className="flex flex-col min-w-0">
                    <span className="text-base text-foreground font-semibold leading-snug truncate">{undefined.name}</span>
                    <span className="text-base text-foreground/75 leading-snug truncate">{undefined.role}</span>
                  </div>
                </div>
                <Button text={undefined.buttonText} href={undefined.buttonHref} variant="primary" />
              </div>
            </>
          )}
        </div>
      </div>
    </section>
  );
};

export default function FaqSection() {
  return (
    <div data-webild-section="faq" data-section="faq" id="faq">
      <FaqInline />
    </div>
  );
}
