// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Information"
          title="NEED TO KNOW"
          categories={[
            {
              name: "Visiting",
              items: [
                {
                  question: "Where are you located?",
                  answer: "We are located right in the heart of Columbia, South Carolina.",
                },
                {
                  question: "Are you open on Sundays?",
                  answer: "Yes, we serve fresh soul food all week long.",
                },
              ],
            },
            {
              name: "Ordering",
              items: [
                {
                  question: "Do you offer catering?",
                  answer: "Absolutely, reach out to us for your next event.",
                },
                {
                  question: "Can I order online?",
                  answer: "Yes, use our website to place your order.",
                },
              ],
            },
          ]}
          textAnimation="fade-blur"
          description="Common questions about our kitchen and how to get your hands on our food."
        />
        </SectionErrorBoundary>
      </div>
  );
}
