// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplit from '@/components/sections/hero/HeroSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplit
        tag="📍 Columbia, South Carolina"
        title="SOUL FOOD MADE TO TASTE LIKE HOME."
        description="Comforting Southern favorites, generous plates, and homemade flavor served with love in Columbia, SC."
        primaryButton={{"href":"#order","text":"ORDER NOW"}}
        secondaryButton={{"text":"VIEW MENU","href":"#menu"}}
        imageSrc="https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070757528-w5tn76jd.webp"
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
