// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "signature-dishes" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SignatureDishesSection(): React.JSX.Element {
  return (
    <div id="signature-dishes" data-section="signature-dishes">
        <SectionErrorBoundary name="signature-dishes">
              <FeaturesImageBento
          tag="Our Favorites"
          title="THE MENU THAT WILL BRING YOUR TASTE BUDS TO LIFE"
          description="Explore the signature dishes that make Taste And See a local favorite in Columbia."
          items={[
            {
              title: "Turkey Wings",
              description: "Tender, flavorful wings with classic sides.",
              imageSrc: "http://img.b2bpic.net/free-photo/family-sitting-table-with-backed-ham_23-2147947986.jpg",
            },
            {
              title: "Pork Chops",
              description: "Hearty chops with Southern seasoning.",
              imageSrc: "http://img.b2bpic.net/free-photo/pork-chop-steak_1339-5911.jpg",
            },
            {
              title: "Lamb Chops",
              description: "Premium soul food, cooked to perfection.",
              imageSrc: "http://img.b2bpic.net/free-photo/cooked-lamb-ribs-front-view_23-2148516965.jpg",
            },
            {
              title: "Oxtails",
              description: "Slow-cooked savory, rich comfort food.",
              imageSrc: "http://img.b2bpic.net/free-photo/grilled-lamb-chops_1203-9879.jpg",
            },
            {
              title: "Mac & Cheese",
              description: "Creamy, baked-to-order Southern style.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070727441-qfbye5ui.webp",
            },
            {
              title: "Rice & Gravy",
              description: "The ultimate Southern comfort staple.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070662778-t3nkrha7.webp",
            },
            {
              title: "Cornbread",
              description: "Golden, moist, and freshly baked.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Db0miCCMRaaN0onIJ91PjmSp14/uploaded-1787070662778-t3nkrha7.webp",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
